#	This file is here so that the plugin/engine can
#	run standard rails rake tasks.
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3	
#  database: ":memory:"
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
#  database: ":memory:"
production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
#  database: ":memory:"
